{% set name = "filepattern" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PolusAI/filepattern/archive/v{{ version }}.tar.gz
  sha256: 3fbe3991c5bccd3d47375fff14df9339ec6b57acaf9e08d20811470978a73571

build:
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - cmake
    - make  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - git
  host:
    - python
    - setuptools
    - pip
    - pybind11
  run:
    - python

test:
  imports:
    - filepattern
  commands:
    - pip check
  requires:
    - pip
    - pytest

about:
  home: https://github.com/PolusAI/filepattern
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JesseMckinzie
